[project]
name = "my_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.28.0",
    "gradio>=5.41.0",
    "ipykernel>=6.30.1",
    "python-dotenv>=1.1.1",
]
